/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as LocalePostsSlugRouteImport } from './routes/$locale/posts/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$locale/$',
  path: '/$locale/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalePostsSlugRoute = LocalePostsSlugRouteImport.update({
  id: '/$locale/posts/$slug',
  path: '/$locale/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/posts/$slug': typeof LocalePostsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/posts/$slug': typeof LocalePostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/posts/$slug': typeof LocalePostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$locale/$' | '/$locale/' | '/$locale/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$locale/$' | '/$locale' | '/$locale/posts/$slug'
  id: '__root__' | '/' | '/$locale/$' | '/$locale/' | '/$locale/posts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocalePostsSlugRoute: typeof LocalePostsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$locale/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/posts/$slug': {
      id: '/$locale/posts/$slug'
      path: '/$locale/posts/$slug'
      fullPath: '/$locale/posts/$slug'
      preLoaderRoute: typeof LocalePostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocalePostsSlugRoute: LocalePostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
